name: Weekly Project Run

on:
  schedule:
    # Запуск каждый понедельник в 8:00 UTC
    - cron: '0 8 * * 1'
  
  # Позволяет запускать workflow вручную
  workflow_dispatch:

jobs:
  run-project:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build project
      run: dotnet build --no-restore --configuration Release
      
    - name: Run project
      run: dotnet run --configuration Release --no-build
      env:
        Telegram__BotToken: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        Telegram__ChatId: ${{ secrets.TELEGRAM_CHAT_ID }}
