name: Weekly Project Run

on:
  schedule:
    # Запуск каждый понедельник в 6:00 UTC
    - cron: '0 6 * * *'
  
  # Позволяет запускать workflow вручную
  workflow_dispatch:

jobs:
  run-project:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build project
      run: dotnet build --no-restore --configuration Release
      
    - name: Debug environment variables
      run: |
        echo "Checking environment variables..."
        echo "Telegram__BotToken length: ${#Telegram__BotToken}"
        echo "Telegram__ChatId length: ${#Telegram__ChatId}"
        if [ -z "$Telegram__BotToken" ]; then
          echo "❌ Telegram__BotToken is empty or not set"
        else
          echo "✅ Telegram__BotToken is set (${#Telegram__BotToken} characters)"
        fi
        if [ -z "$Telegram__ChatId" ]; then
          echo "❌ Telegram__ChatId is empty or not set"
        else
          echo "✅ Telegram__ChatId is set (${#Telegram__ChatId} characters)"
        fi
      env:
        Telegram__BotToken: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        Telegram__ChatId: ${{ secrets.TELEGRAM_CHAT_ID }}
      
    - name: Run project
      run: dotnet run --configuration Release --no-build
      env:
        Telegram__BotToken: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        Telegram__ChatId: ${{ secrets.TELEGRAM_CHAT_ID }}